# Generated by Django 3.2.15 on 2022-11-20 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ціна')),
                ('promotion', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Акція в %')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='Опис')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('diameter', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Ширина')),
                ('booster', models.BooleanField(default=False, verbose_name='Бустер')),
                ('draft', models.BooleanField(default=False, verbose_name='Наявність')),
            ],
        ),
    ]
