# Generated by Django 3.2.15 on 2022-12-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_wick_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wick',
            name='url',
            field=models.SlugField(max_length=130),
        ),
    ]
