# Generated by Django 3.2.15 on 2022-12-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='back',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото вверху'),
        ),
    ]
